### ISSUE TITLE
Can you document approximate sizes for logos and background images?

### ISSUE THREAD

**Issue by pjz** [molivier/nest#13]
...or are they scaled automatically down somehow?

**Comment by molivier** [comment]
You're right the README needs a section about images sizes.

The `header-nav` have a fixed heigth of 100px. This is the max size for the logo without css modification.

The `min-height` for the background header is 360px. The image is displayed using `background-size: cover;` which scale the background image to be as large as possible so that the background area is completely covered by the background image. If smaller than screen, the image is repeated to fit the background area.

Does this help?
